### ISSUE TITLE
dotnet failed with exit code 1, related to SDK version

### ISSUE THREAD

**Issue by DamonStamper** [MicrosoftDocs/mslearn-tailspin-spacegame-web#1288]
https://docs.microsoft.com/en-us/learn/modules/create-a-build-pipeline/6-create-the-pipeline

Copying the azure-pipelines.yml contents from the above URL results in a failure at the "Build the project - Release" task. Errors are
##[error]Error: The process '/opt/hostedtoolcache/dotnet/dotnet' failed with exit code 1
##[error]Dotnet command failed with non-zero exit code on the following projects : /home/vsts/work/1/s/Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj

I corrected this by updating the below code from
```
steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.100'
  inputs:
    packageType: sdk
    version: 3.1.100
```

to
```
steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 2.2.x'
  inputs:
    packageType: sdk
    version: 2.2.x
```

**Comment by BTejaS** [comment]
Below solution can be used as alternative
- Backup azure-pipelines.yaml
- Reset to last available merge prior to .NET Core 3.1
`git reset --hard 435520f`
- Copy backup of azure-pipelines.yaml to top level directory of repository
- Commit azure-pipelines.yaml
`git add azure-pipelines.yaml`
`git commit -m 'azure pipelines ci'`
- Force push to GitHub Repository
`git push --force`

> Pipeline should start automatically. If not, Click 'Run pipeline' (Refer Azure DevOps Documentation)

> Caution: `git reset --hard` discards lastest changes

**Comment by ChPfisterer** [comment]
In the **unit-tests** branch, as the project files are updated to use SDK version 3.1, the variables for .NET SDK version at the **azure-pipeline.yml** file should be updated as follows:
```
variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '3.1.100'
```
Otherwise you get the mentioned error code from pipeline.
